import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import {
  SidebarProvider,
  SidebarTrigger,
  SidebarInset,
} from "@/components/ui/sidebar";

import { AppSidebar } from "@/components/app-sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = localFont({
  src: [
    {
      path: "../public/fonts/InterVariable.woff2",
      weight: "100 900",
    },
    {
      path: "../public/fonts/InterVariable-Italic.woff2",
      weight: "100 900",
      style: "italic",
    },
  ],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HEADER_HEIGHT = "64px";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased overflow-hidden font-sans`}
        style={{ "--header-height": HEADER_HEIGHT } as React.CSSProperties}
      >
        <header className="flex h-[--header-height] items-center border-b border-zinc-200 px-5 z-20">
          <h1 className="text-xl font-medium">Eisenhower Matrix</h1>
        </header>
        <SidebarProvider className="bg-zinc-50">
          <div className="flex-1 pt-5 pb-8 px-8 h-full min-h-[calc(100svh-var(--header-height))] bg-zinc-50">
            <header className="mb-5 flex shrink-0 items-center justify-between h-12 gap-4">
              <h2 className="text-lg font-medium">Eisenhower Matrix</h2>
              <SidebarTrigger />
            </header>
            <div className="h-[calc(100svh-(var(--header-height) + 48px))]">
              {children}
            </div>
          </div>
          <AppSidebar />
        </SidebarProvider>
      </body>
    </html>
  );
}
